### ISSUE TITLE
Creating a Table

### ISSUE THREAD

**Issue by aikruger** [h-sphere/sql-seal#12] opened 2024-10-05 19:32 UTC
I am not sure if I am following correctly but in obsidian windows desktop, TABLE newtable=file(new.csv) should create a new table in the sqlite database? This does not seem to be working. I get no such table error. When I create a table in the sqlite database by other means it still cannot find that table.
Excellent and much needed idea

**Comment by kulak-at** [comment] 2024-11-03 21:26
Hi, I identified issue with some keys and headers in CSV file not converting properly when loaded. I've just released the new version (0.9.1) which might fix your issue. Please test it and get back to me if it helps with the problem. If not, please send me the csv file you're using (or at least a small snippet of it) and exact content of the `sqlseal` block you're trying to execute.

**Comment by kulak-at** [comment] 2024-11-24 16:31
@aikruger New version (0.11) was released today including a lot of fixes and new CSV viewer. Please test it out and let me know if that helps you with your problems.

**Comment by aikruger** [comment] 2024-11-30 18:34
Awesome addition, thanks is this great

**Comment by kulak-at** [comment] 2024-12-01 11:00
Hi, you can define multiple tables and then run query with them:

```sql
TABLE a = file(myfirstfile.csv)
TABLE b = file(mysecondfile.csv)

SELECT * FROM a JOIN b ON a.id=b.foreign_id
```

You will need to adjust names of files and the column names but that should help you get started with that!

As the problem is now resolved I am closing this issue. Do not hesitate to ask more questions in here or on the Discord channel here: https://discord.gg/ZMRnFeAWXb

**Closed by kulak-at** 2024-12-01 11:00 UTC
